title: Serena Wu
description: Personal Portfolio
theme: just-the-docs

url: https://serena6688.github.io/serenaintech/

# Navigation links
nav:
  - title: Home
    url: /
  - title: Data Projects
    url: /data-project
  - title: Software Projects
    url: /software-project
  - title: Personal Life
    url: /personal-life

