title: Your Name
description: Personal Portfolio
theme: just-the-docs

url: https://your-github-username.github.io

# Navigation links
nav:
  - title: Home
    url: /
  - title: Data Projects
    url: /data-project
  - title: Software Projects
    url: /software-project
  - title: Personal Life
    url: /personal-life

# Add resume download link to the footer or navbar
aux_links:
  Resume (PDF): /assets/resume.pdf