title: Serena Wu
description: Personal Portfolio
theme: just-the-docs

url: https://serena6688.github.io/serenaintech/
baseurl: "/serenaintech"

search_enabled: false

just_the_docs:
  show_sidebar: false

# Navigation links
nav:
  - title: Home
    url: /
  - title: My Projects
    url: /projects
#  - title: Software Projects
#    url: /software-project
  - title: Life Outside Code
    url: /life-outside-code


aux_links:
  luyaowutech@gmail.com: mailto:luyaowutech@gmail.com