title: Your Name  # Website title
logo: "/path/to/your/logo.png" # Optional logo
# description: "A personal website" # Optional description

nav_order:
  - home.md
  - data-projects.md
  - software-projects.md
  - personal-life.md